theme: jekyll-theme-minimal
description: Welcome to the Earth Data Provenance Workshop. March 27-29, 2018 | eScience Institute, Seattle, WA
image: http://www.esipfed.org/wp-content/uploads/2016/12/ESIP-final-logo.png
avatar: http://www.esipfed.org/wp-content/uploads/2016/12/ESIP-final-logo.png
